[package]
name = "poker-odds-rs"
version = "0.1.0"
edition = "2021"

[dependencies]
rand = "0.8.5"
strum = "0.26.3"
strum_macros = "0.26.4"

[profile.dev]
opt-level = 3           
overflow-checks = false   
